name: CI 

on: 
  push:
    branches: ["main"]


jobs: 
  builds: 
    runs-on: ubuntu-latest

    steps: 
      
      - name: Checkout SCM 
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: pip install pytest flask-testing 

      - name: Run unit test 
        run: pytest 

